# Generated by Django 2.0.2 on 2018-04-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_call', models.CharField(choices=[('start', 'Start'), ('end', 'End')], max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('call_id', models.BigIntegerField()),
                ('source', models.CharField(max_length=20, null=True)),
                ('destination', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'call',
                'verbose_name_plural': 'calls',
            },
        ),
        migrations.AlterUniqueTogether(
            name='call',
            unique_together={('call_id', 'type_call')},
        ),
    ]
