# Generated by Django 2.0.2 on 2018-04-08 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=20)),
                ('start_call', models.DateTimeField()),
                ('duration_call', models.FloatField()),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name': 'Call Billing',
                'verbose_name_plural': 'Call Billings',
            },
        ),
        migrations.CreateModel(
            name='PhoneBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=4)),
                ('amount', models.FloatField()),
            ],
            options={
                'verbose_name': 'Phone Bill',
                'verbose_name_plural': 'Phone Billings',
            },
        ),
        migrations.AlterUniqueTogether(
            name='phonebill',
            unique_together={('source', 'month', 'year')},
        ),
        migrations.AddField(
            model_name='callbilling',
            name='phone_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PhoneBill'),
        ),
    ]
