# Generated by Django 2.0.2 on 2018-04-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180408_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.CharField(max_length=5)),
                ('end_hour', models.CharField(max_length=5)),
                ('call_charge', models.FloatField()),
                ('standing_charge', models.FloatField()),
            ],
            options={
                'verbose_name': 'Tariff',
                'verbose_name_plural': 'Tariffs',
            },
        ),
    ]
