# Generated by Django 2.0.2 on 2018-04-15 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tariff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tariff',
            old_name='end_hour',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='tariff',
            old_name='start_hour',
            new_name='start_time',
        ),
    ]
